name: MCore
version: '${version}'
main: com.github.matin2.mcore.MCore
loader: com.github.matin2.mcore.MCoreLoader
api-version: '26.1.2'
load: STARTUP
authors: [ Matin3000 ]
dependencies:
  server:
    packetevents:
      load: BEFORE
      required: false
    SkinsRestorer:
      load: BEFORE
      required: false
